### PR TITLE
Fix client.watch() raising ConnectionTimeoutError on client timeout

### PR DESCRIPTION
**Pull request by mk-fg**
**Expected result:**
Starting client.watch() and waiting for events there can take an arbitrarily long time.
E.g. there can be no changes to the key for an hour, and nothing will break.

**Actual result:**
`async for event in w:` loop raises `aetcd.exceptions.ConnectionTimeoutError: Deadline Exceeded` after a couple seconds (client timeout, 15s default).

test_watch_ignores_timeout should illustrate the issue with timeout= parameter passed to _watchstub.Watch call, and maybe useful to test for regression of that kind, but not sure if really needed there.

### CODE REVIEW

**Comment by martyanov** [comment]
Thanks for reporting this! I'm aware of the issue and ok with removing the `timeout`, but the problem is `watchstub` is not the only place affected by the global timeout, probably that is every rpc stream call. So I need to think about it more thoroughly, as it affects the public API and should be reflected in documentation. If you have any thoughts about the issue please share.

I'll get back to this later.

**Comment by mk-fg** [comment]
I think it doesn't make sense for streaming transports/sockets, hence only present as `socket.settimeout()` in blocking API and removed in asyncio.
But it makes sense for request-response APIs, where you generally want to have some sanity-check on all get/put/etc ops, which is why it exists in e.g. aiohttp.

Also aiohttp folks seem to have realized that this should be more nuanced than one nebulous "timeout" value, and introduced extensible ClientTimeout structure, deprecating all old floats that were accreting in request/session over time.
https://docs.aiohttp.org/en/stable/client_reference.html#aiohttp.ClientTimeout

Iirc watch request is special, in that it is not expected to get proper response, so either special timeout should apply there or none at all, and definitely not such one-global-float value.

So imo one global float timeout= for session is fine as a simple and relatively future-proof solution, and can be easily extended later to receive more complex struct with maybe timeout for each operation, something like transport timeouts (e.g. tcp/grpc connect/read/write/etc) or whatever.
Extended without even deprecating simple catch-all float value which can still work to set all granular timeouts to what they'd roughly be with that value before they were introduced, and useful for most folks who don't actually care about such details.

But don't know if I fully understand why global timeout might be bad - presumably user can always set it to infinity and use wait_for to limit specific calls, but as mentioned, seem to be very useful for most use-cases where roughly "everything not hanging forever" is perfectly fine.

**Comment by martyanov** [comment]
Changes pushed to master with https://github.com/martyanov/aetcd/commit/26a2e0df635a2889a7de6a05bdd894545815d8c3.

**Comment by martyanov** [comment]
I'm sorry, I don't know how to `git cherry-pick -S` and let GitHub know that the changes are already in master.

**Comment by martyanov** [comment]
I tried to update the branch via GitHub UI, but it was probably `git pull --merge` not `git pull --rebase`, pretty stupid. Treat as merged please.

**Pull request closed without merging**
